# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Camus
email: mail@stephanemourey.fr
description: >- # this means to ignore newlines until "baseurl:"
  Intention-driven programming language for AIs and humans
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://taophp.github.io/Camus/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: taophp
remote_theme: "jekyll/minima@1e8a445"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
# Blog configuration
blog:
  recent_posts_count: 2 # Number of recent posts to show on homepage
  show_excerpts: true # Show post excerpts on blog index
  excerpt_length: 30 # Number of words in excerpts

minima:
  hide_site_feed_link: false # Enable feed link in footer
  skin: auto
  nav_pages:
    - url: "/blog/"
      title: "Blog"
    - 10-quickstart.md
    - url: "https://github.com/taophp/Camus/discussions"
      title: "Community"
      target: "_blank"
